---
- name: Apache Tomcat Kurulumu
  hosts: linux_servers
  become: yes

  vars:
    tomcat_version: "10.1.19"
    java_version: "11"

  tasks:
    - name: Java kurulumu
      apt:
        name: "openjdk-{{ java_version }}-jdk"
        state: present
        update_cache: yes

    - name: Tomcat kullanıcısı oluştur
      user:
        name: tomcat
        home: /opt/tomcat
        shell: /bin/false
        system: yes

    - name: Tomcat dizini oluştur
      file:
        path: /opt/tomcat
        state: directory
        owner: tomcat
        group: tomcat

    - name: Tomcat'i indir ve kur
      unarchive:
        src: "https://dlcdn.apache.org/tomcat/tomcat-10/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: /opt/tomcat
        remote_src: yes
        owner: tomcat
        group: tomcat
        extra_opts: [--strip-components=1]
